version: '2.1'

volumes:
   #db-backups:
   geoserver-data: /datadisk/geoserver
   geo-db-data: /datadisk/postgresql

networks:
  traefik_nwproxy:
    external: true
  bridge:
    external: false

services:
   db:
      image: kartoza/postgis:9.6-2.4
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - "5432:5432"
      env_file:
      - docker-env/db.env
      restart: on-failure
      healthcheck:
        test: "exit 0"

   geoserver:
      image: kartoza/geoserver:2.15.0
      labels:
        - "traefik.backend=geoserver"
        - "traefik.frontend.rule=Host:geoserver.address.gov.sa"
        - "traefik.docker.network=traefik_nwproxy"    
        - "traefik.port=80"      
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "80:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      depends_on:
        db:
          condition: service_healthy
      networks:
        - bridge
        - traefik_nwproxy              
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3


  #  db-dbbackups:
  #    image: kartoza/pg-backup:9.6
  #    volumes:
  #    - db-backups:/backups
  #    env_file:
  #    - docker-env/db-backups.env
  #    restart: on-failure
  #    depends_on:
  #      db:
  #        condition: service_healthy
